/*
###########################################################################
# File..................: Sample_Standard_ClsTrgHlpr
# Class Type............: Trigger Helper
# Created by............: Naveen Ila
# Created Date..........: 02-Aug-2016
# Last Modified by......: 
# Last Modified Date....: 
# Description...........: Sample Trigger Helper Class
# VF page...............: 
# Change Log:
###########################################################################
*/
public with sharing class Sample_Standard_ClsTrgHlpr {

	// Before Insert Events
    public static void beforeInsert(List<Object> objList){

    }

    // After Insert Events
    public static void afterInsert(List<Object> objList){

    }

    // Before Update Events
    public static void beforeUpdate(List<Object> objList){

    }

    // After Update Events
    public static void afterUpdate(List<Object> objList){

    }
}