/*
###########################################################################
# File..................: Sample_Standard_CtrlExtnsion
# Class Type............: Standard Controller Extension
# Created by............: Naveen Ila
# Created Date..........: 02-Aug-2016
# Last Modified by......: 
# Last Modified Date....: 
# Description...........: Sample Standard Controller Extension
# VF page...............: 
# Change Log:
###########################################################################
*/
public with sharing class Sample_Standard_CtrlExtnsion {
	//Constructor with standard controller object as param
    public Sample_Standard_CtrlExtnsion(ApexPages.StandardController con) {
        
    }
}