/*
###########################################################################
# File..................: Sample_Standard_SchClsHlpr
# Class Type............: Schedule Helper Class
# Created by............: Naveen Ila
# Created Date..........: 02-Aug-2016
# Last Modified by......: 
# Last Modified Date....: 
# Description...........: Sample Schedule Helper Class
# VF page...............: 
# Change Log:
###########################################################################
*/
public with sharing class Sample_Standard_SchClsHlpr {
    
}