/*
###########################################################################
# File..................: Sample_Standard_SetCtrl
# Class Type............: Standard Set Controller
# Created by............: Naveen Ila
# Created Date..........: 02-Aug-2016
# Last Modified by......: 
# Last Modified Date....: 
# Description...........: Sample Standard Set Controller
# VF page...............: 
# Change Log:
###########################################################################
*/
public with sharing class Sample_Standard_SetCtrl {

    //Constructor with standard set controller object as param
    public Sample_Standard_SetCtrl(ApexPages.StandardSetController con) {
        
    }
}