/*
###########################################################################
# File..................: Sample_Standard_Cls
# Class Type............: Basic Class
# Version...............: 1
# Created by............: Naveen Ila
# Created Date..........: 02-Aug-2016
# Last Modified by......:
# Last Modified Date....:
# Description...........: This was a standard Basic class.
# VF page...............:
# Change Log:
*/

public with sharing class Sample_Standard_Cls {
    //Public variables 

	//Private Variables

	//Methods

	/**
	 * @name         :   smapleMethod
	 * @description  :   This method is a sample method
	 * @param        :   
	 * @return       :   
 	**/  
    public void smapleMethod(){

    }
}