/*
###########################################################################
# File..................: Sample_Standard_CustmCtrlCls
# Class Type............: Custom Controller Class
# Created by............: Naveen Ila
# Created Date..........: 02-Aug-2016
# Last Modified by......: 
# Last Modified Date....: 
# Description...........: Sample Custom Controller Class
# VF page...............: Sample_Standard_VFPage
# Change Log: 
###########################################################################
*/

public with sharing class Sample_Standard_CustmCtrlCls {
	//Public variables 

	//Private Variables

	// Default Constructor
    public Sample_Standard_CustmCtrlCls() {
        
    }

    //Methods


    /**
	 * @name         :   smapleMethod
	 * @description  :   This method is a sample method
	 * @param        :   
	 * @return       :   
 	**/  
    public void smapleMethod(){

    }
}