/*
###########################################################################
# File..................: Sample_Standard_SchCls
# Class Type............: Schedule Class
# Created by............: Naveen Ila
# Created Date..........: 02-Aug-2016
# Last Modified by......: 
# Last Modified Date....: 
# Description...........: Sample Schedule Class
# VF page...............: 
# Change Log:
###########################################################################
*/
global class Sample_Standard_SchCls implements Schedulable {

	// Execute Method
    global void execute(SchedulableContext sc) {
        
    }
}