/*
###########################################################################
# File..................: Sample_Standard_BtchClsHlpr
# Class Type............: Batch Helper Class
# Created by............: Naveen Ila
# Created Date..........: 02-Aug-2016
# Last Modified by......: 
# Last Modified Date....: 
# Description...........: Sample Batch Class Helper
# VF page...............: 
# Change Log:
###########################################################################
*/
public with sharing class Sample_Standard_BtchClsHlpr {
    
}